In [10]:
import pandas as pd
mode="hate_category"
#mode="hate_category"


def csv_to_json(csv_file,json_file, mode, upper_limit=0, down_limit=0):
    df = pd.read_csv(csv_file)
    #df = df.drop('done', 1)
    df = df.drop('Unnamed: 0', 1)

    #for Hate Speech Type Training
    if mode=="hate_type":
        df = df.drop('label Protected Category ', 1)
        df = df.rename(columns = {"label hate Speech Type":"label"})

    #for Hate Speech Type Training 
    elif mode=="hate_category":
        df = df.drop('label hate Speech Type', 1)
        df = df.rename(columns = {"label Protected Category ":"label"})
    else: 
        print("not a valid mode")
        return 
    if upper_limit!=0 and down_limit==0:
        df=df.drop(df.index[upper_limit:])
    elif upper_limit==0 and down_limit!=0:
        df=df.drop(df.index[:down_limit])
    elif upper_limit!=0 and down_limit!=0:
        df=df.drop(df.index[upper_limit:down_limit])
        
    #df.to_json(json_file, orient="records", lines="True")
    global df_type
    df_type=df
    print("saved "+json_file+" at current directory")

csv_to_json("classification  - train.csv", "test_type.jsonl", mode)

saved test_type.jsonl at current directory

In [2]:
#hate category 1+2
df_type["label_original"]=df_type["label"]
df_type["label"] = df_type["label"].apply(lambda x:1 if x==2 else x)
df_type.loc[df_type['label'] == 1]
#hate category 3+5
df_type["label"] = df_type["label"].apply(lambda x:3 if x==5 else x)
df_type.loc[df_type['label'] == 3]
#hate category 7+8
df_type["label"] = df_type["label"].apply(lambda x:7 if x==8 else x)
df_type.loc[df_type['label_original'] == 7]
df_type.loc[df_type['id'] == 13806]

,id,img,label,text,label_original
8348,13806,img/13806.png,7,opens ice cream shop only sells shakes,8

In [3]:
#hate category 3-->2
df_type["label_move"]=df_type["label"]
df_type["label"] = df_type["label"].apply(lambda x:2 if x==3 else x)
df_type.loc[df_type['label'] == 2]
#hate category 4-->3
df_type["label"] = df_type["label"].apply(lambda x:3 if x==4 else x)
df_type.loc[df_type['label'] == 3]
#hate category 6-->4
df_type["label"] = df_type["label"].apply(lambda x:4 if x==6 else x)
df_type.loc[df_type['label'] == 4]
#hate category 7-->5
df_type["label"] = df_type["label"].apply(lambda x:5 if x==7 else x)
df_type.loc[df_type['label'] == 5]

df_type

,id,img,label,text,label_original,label_move
0,42953,img/42953.png,0,its their character not their color that matters,0,0
1,23058,img/23058.png,0,don't be afraid to love again everyone is not ...,0,0
2,13894,img/13894.png,0,putting bows on your pet,0,0
3,37408,img/37408.png,0,i love everything and everybody! except for sq...,0,0
4,82403,img/82403.png,0,"everybody loves chocolate chip cookies, even h...",0,0
...,...,...,...,...,...,...
8495,10423,img/10423.png,1,nobody wants to hang auschwitz me,1,1
8496,98203,img/98203.png,1,when god grants you a child after 20 years of ...,1,1
8497,36947,img/36947.png,2,gays on social media: equality! body positivit...,3,3
8498,16492,img/16492.png,4,having a bad day? you could be a siamese twin ...,6,6
8499,15937,img/15937.png,1,i hate muslims too they take their religion to...,2,1

In [4]:
#save train_cat 
df_type = df_type.drop('label_original', 1)
df_type = df_type.drop('label_move', 1)

df_type.to_json("train_cat.jsonl", orient="records", lines="True")

In [49]:
#samples for dev_unseen_cat
df=pd.read_json('train_cat.jsonl', lines="True")
dev0=df.loc[df['label']==0].sample(n=300)
dev1=df.loc[df['label']==1].sample(n=300)
dev2=df.loc[df['label']==2].sample(n=32)
dev3=df.loc[df['label']==3].sample(n=39)
dev4=df.loc[df['label']==4].sample(n=23)
dev5=df.loc[df['label']==5].sample(n=34)

dev=dev0
dev=dev.append(dev1)
dev=dev.append(dev2)
dev=dev.append(dev3)
dev=dev.append(dev4)
dev=dev.append(dev5)


cond = df['id'].isin(dev['id'])
df.drop(df[cond].index, inplace = True)

df.to_json("train_cat.jsonl", orient="records", lines="True")
dev.to_json("dev_unseen_cat.jsonl", orient="records", lines="True")

In [50]:
#samples for test_unseen_cat
df=pd.read_json('train_cat.jsonl', lines="True")
dev0=df.loc[df['label']==0].sample(n=100)
dev1=df.loc[df['label']==1].sample(n=100)
dev2=df.loc[df['label']==2].sample(n=25)
dev3=df.loc[df['label']==3].sample(n=25)
dev4=df.loc[df['label']==4].sample(n=20)
dev5=df.loc[df['label']==5].sample(n=25)

dev=dev0
dev=dev.append(dev1)
dev=dev.append(dev2)
dev=dev.append(dev3)
dev=dev.append(dev4)
dev=dev.append(dev5)


cond = df['id'].isin(dev['id'])
df.drop(df[cond].index, inplace = True)

df.to_json("train_cat.jsonl", orient="records", lines="True")
dev.to_json("test_unseen_cat.jsonl", orient="records", lines="True")

In [43]:
#hate type 1+2
df_type["label_original"]=df_type["label"]
df_type["label"] = df_type["label"].apply(lambda x:1 if x==2 else x)
df_type.loc[df_type['label'] == 1]
#hate type 3+9
df_type["label"] = df_type["label"].apply(lambda x:3 if x==9 else x)
df_type.loc[df_type['label'] == 3]
#hate type 4+5
df_type["label"] = df_type["label"].apply(lambda x:4 if x==5 else x)
df_type.loc[df_type['label_original'] == 5]
#hate type 4+5+6
df_type["label"] = df_type["label"].apply(lambda x:4 if x==6 else x)
df_type.loc[df_type['label'] == 4]
#hate type 4+5+6
df_type["label"] = df_type["label"].apply(lambda x:4 if x==6 else x)
df_type.loc[df_type['label'] == 4]
#hate type 11+12
df_type["label"] = df_type["label"].apply(lambda x:11 if x==12 else x)
df_type.loc[df_type['label'] == 11]

,id,img,label,text,label_original
65,20619,img/20619.png,11,when you beat the shit out of the tranny hooke...,12
69,74530,img/74530.png,11,what's the difference between a jew and a pizz...,12
94,75321,img/75321.png,11,cannibal tribe from indonesia will take muslim...,12
122,54102,img/54102.png,11,i'm uncertain where i stand on abortion i like...,12
136,26759,img/26759.png,11,that look when you wanna cut a bitch but you r...,12
...,...,...,...,...,...
8469,43295,img/43295.png,11,gotta run away from those niggers,11
8477,39472,img/39472.png,11,i'm not an islamophobe i just can't stand the ...,11
8491,14275,img/14275.png,11,i have 72 nukes aimed at israel if these damn ...,12
8494,21345,img/21345.png,11,"when you re out in public, and your muslim act...",12
8499,15937,img/15937.png,11,i hate muslims too they take their religion to...,11

In [44]:
#hate type 3-->2
df_type["label_move"]=df_type["label"]
df_type["label"] = df_type["label"].apply(lambda x:2 if x==3 else x)
df_type.loc[df_type['label'] == 2]
#hate type 4-->3
df_type["label"] = df_type["label"].apply(lambda x:3 if x==4 else x)
df_type.loc[df_type['label'] == 3]
#hate type 7-->4
df_type["label"] = df_type["label"].apply(lambda x:4 if x==7 else x)
df_type.loc[df_type['label'] == 5]
#hate type 8-->5
df_type["label"] = df_type["label"].apply(lambda x:5 if x==8 else x)
df_type.loc[df_type['label'] == 5]
#hate type 10-->6
df_type["label"] = df_type["label"].apply(lambda x:6 if x==10 else x)
df_type.loc[df_type['label'] == 6]
#hate type  11â€”> 7
df_type["label"] = df_type["label"].apply(lambda x:7 if x==11 else x)
df_type.loc[df_type['label'] == 7]

df_type

,id,img,label,text,label_original,label_move
0,42953,img/42953.png,0,its their character not their color that matters,0,0
1,23058,img/23058.png,0,don't be afraid to love again everyone is not ...,0,0
2,13894,img/13894.png,0,putting bows on your pet,0,0
3,37408,img/37408.png,0,i love everything and everybody! except for sq...,0,0
4,82403,img/82403.png,0,"everybody loves chocolate chip cookies, even h...",0,0
...,...,...,...,...,...,...
8495,10423,img/10423.png,5,nobody wants to hang auschwitz me,8,8
8496,98203,img/98203.png,2,when god grants you a child after 20 years of ...,9,3
8497,36947,img/36947.png,2,gays on social media: equality! body positivit...,9,3
8498,16492,img/16492.png,4,having a bad day? you could be a siamese twin ...,7,7
8499,15937,img/15937.png,7,i hate muslims too they take their religion to...,11,11

In [45]:
df_type = df_type.drop('label_original', 1)
df_type = df_type.drop('label_move', 1)

df_type.to_json("train_type.jsonl", orient="records", lines="True")

In [41]:
#chech, how many samples in each class
df_type.loc[df_type['label']==7]

,id,img,label,text
65,20619,img/20619.png,7,when you beat the shit out of the tranny hooke...
69,74530,img/74530.png,7,what's the difference between a jew and a pizz...
94,75321,img/75321.png,7,cannibal tribe from indonesia will take muslim...
122,54102,img/54102.png,7,i'm uncertain where i stand on abortion i like...
136,26759,img/26759.png,7,that look when you wanna cut a bitch but you r...
...,...,...,...,...
8469,43295,img/43295.png,7,gotta run away from those niggers
8477,39472,img/39472.png,7,i'm not an islamophobe i just can't stand the ...
8491,14275,img/14275.png,7,i have 72 nukes aimed at israel if these damn ...
8494,21345,img/21345.png,7,"when you re out in public, and your muslim act..."
8499,15937,img/15937.png,7,i hate muslims too they take their religion to...

In [46]:
#samples for dev_unseen_type
df=pd.read_json('train_type.jsonl', lines="True")
dev0=df.loc[df['label']==0].sample(n=125)
dev1=df.loc[df['label']==1].sample(n=31)
dev2=df.loc[df['label']==2].sample(n=125)
dev3=df.loc[df['label']==3].sample(n=52)
dev4=df.loc[df['label']==4].sample(n=26)
dev5=df.loc[df['label']==5].sample(n=59)
dev6=df.loc[df['label']==6].sample(n=17)
dev7=df.loc[df['label']==7].sample(n=51)

dev=dev0
dev=dev.append(dev1)
dev=dev.append(dev2)
dev=dev.append(dev3)
dev=dev.append(dev4)
dev=dev.append(dev5)
dev=dev.append(dev6)
dev=dev.append(dev7)


cond = df['id'].isin(dev['id'])
df.drop(df[cond].index, inplace = True)

df.to_json("train_type.jsonl", orient="records", lines="True")
dev.to_json("dev_unseen_type.jsonl", orient="records", lines="True")

In [47]:
#samples for test_unseen_type
df=pd.read_json('train_type.jsonl', lines="True")
dev0=df.loc[df['label']==0].sample(n=40)
dev1=df.loc[df['label']==1].sample(n=25)
dev2=df.loc[df['label']==2].sample(n=40)
dev3=df.loc[df['label']==3].sample(n=30)
dev4=df.loc[df['label']==4].sample(n=20)
dev5=df.loc[df['label']==5].sample(n=35)
dev6=df.loc[df['label']==6].sample(n=10)
dev7=df.loc[df['label']==7].sample(n=30)

dev=dev0
dev=dev.append(dev1)
dev=dev.append(dev2)
dev=dev.append(dev3)
dev=dev.append(dev4)
dev=dev.append(dev5)
dev=dev.append(dev6)
dev=dev.append(dev7)


cond = df['id'].isin(dev['id'])
df.drop(df[cond].index, inplace = True)

df.to_json("train_type.jsonl", orient="records", lines="True")
dev.to_json("test_unseen_type.jsonl", orient="records", lines="True")

In [203]:
df = pd.read_csv(csv_file)
#df = df.drop('done', 1)
df = df.drop('Unnamed: 0', 1)

#for Hate Speech Type Training 
df = df.drop('label Protected Category ', 1)
df = df.rename(columns = {"label hate Speech Type":"label"})

#for Hate Speech Type Training 
#df = df.drop('label hate Speech Type', 1)
#df = df.rename(columns = {"label Protected Category ":"label"})

df

,id,img,label,text
0,42953,img/42953.png,0,its their character not their color that matters
1,23058,img/23058.png,0,don't be afraid to love again everyone is not ...
2,13894,img/13894.png,0,putting bows on your pet
3,37408,img/37408.png,0,i love everything and everybody! except for sq...
4,82403,img/82403.png,0,"everybody loves chocolate chip cookies, even h..."
...,...,...,...,...
8495,10423,img/10423.png,1,nobody wants to hang auschwitz me
8496,98203,img/98203.png,1,when god grants you a child after 20 years of ...
8497,36947,img/36947.png,1,gays on social media: equality! body positivit...
8498,16492,img/16492.png,1,having a bad day? you could be a siamese twin ...
8499,15937,img/15937.png,1,i hate muslims too they take their religion to...